services:
  app:
    image: node:21
    working_dir: /var/app
    depends_on:
      - medusa
    env_file: 
     - docker/medusa-codegen/default.env
     - .env
    tty: true # to emulate terminal for unquirer to be used
    stdin_open: true
    environment:
      ENV: dev
    volumes:
      - './node_modules:/var/app/node_modules'
      - './package.json:/var/app/package.json'
      - './nodemon.json:/var/app/nodemon.json'
      - './tsconfig.json:/var/app/tsconfig.json'
      - './generated:/var/app/generated'
      - './src:/var/app/src'
    tmpfs:
      - /var/dist
    expose:
      - '8080'
    ports:
      - '8080:8080'
    command: bash -c "npm --no-warnings install && npm run dev"
    networks:
      - ai-docker

  db:
    image: postgres:13
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    restart: always
    networks:
      - ai-docker

  medusa:
    build:
      dockerfile: ./docker/medusa/Dockerfile
    container_name: medusa
    ports:
      - 9000:9000
    working_dir: /var/medusa
    volumes:
      - ./medusa/my-medusa-store:/var/medusa
    depends_on:
      - db
    restart: always
    networks:
      - ai-docker

networks:
  ai-docker:
    external: false
  